version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./api
    container_name: nest-api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: mysql://root@db:3306/auth_db
    depends_on:
      - db

  front:
    build: ./front
    container_name: react-front
    ports:
      - "5173:5173"
    env_file:
      - ./front/.env
    depends_on:
      - api

volumes:
  mysql_data:
