services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./Backend_auth
    container_name: nest-api
    ports:
      - "4000:4000"
    env_file:
      - ./Backend_auth/.env
    environment:
      DATABASE_URL: mysql://root@db:3306/auth_db
    depends_on:
      - db



  front:
    build: ./front_auth
    container_name: next-front
    ports:
      - "3000:3000"
    env_file:
      - ./front_auth/.env
    environment:
      NEXT_PUBLIC_API_URL: http://api:4000
    depends_on:
      - api
    command: npm run dev -- --turbopack -p 3000 -H 0.0.0.0


volumes:
  mysql_data:
